version: "3.8"
services:
    nodeserver:
        build:
            context: ./Backend
        ports:
            - "8082:8082"
    frontend:
        build:
            context: ./Frontend
        ports:
            - "80:80"
            - "443:443"