version: "3.8"
services:
    nodeserver:
        build:
            context: ./Backend
        ports:
            - "8082:8082"
    frontend:
        build:
            context: ./Frontend
        ports:
            - "90:90"
            - "445:445"